
height=float(input("what is your hight foot___ in___"))
age=int(input("what is your age "))
weight = int(input("what is your wight "))
print("user height: ",height)
print("user age: ",age)
print("user Weight: ",weight)
sqhight=(int(height)^2)
bmi=(weight/sqhight)
print("--------------------------------")
print("             BMI                ")
print("--------------------------------")
print("user height: ",height)
print("user age: ",age)
print("user Weight: ",weight)
print("your bmi is :",bmi)